version: "3"
volumes:
  production-database:
services: 
  nginx:
    ports:
      - 80:80

  app: 
    build: 
      context: .
      args: 
        NODE_ENV: production
    command: npm run start
    environment:
      - NODE_ENV=production
      - DATABASE_USERNAME=${DATABASE_USERNAME}
      - DATABASE_PASSWORD=${DATABASE_PASSWORD}
      - SESSION_SECRET=${SESSION_SECRET}

  database:
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
    volumes:
      - production-database:/data/db # Named volume
