version: "3"
services:
  nginx:
    ports:
      - 3000:80

  app:
    build: 
      context: .
      args: 
        NODE_ENV: development
    command: npm run dev
    env_file: ./.env
    volumes:
      - ./:/app # Bind-mount volume
      - /app/node_modules # Anonymous volume
    
  database:
    environment:
      - MONGO_INITDB_ROOT_USERNAME=sirpeace
      - MONGO_INITDB_ROOT_PASSWORD=password