version: "3"

services: 
  nginx:
    image: nginx:stable-alpine
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro

  app: 
    build: .
    depends_on: 
      - database

  database: 
    image: mongo

  redis:
    image: redis