version: "3"
services:
  nginx:
    ports:
      - 3000:80

  app:
    build: 
      context: .
      args: 
        NODE_ENV: development
    volumes:
      - ./:/app # Bind-mount volume
      - /app/node_modules # Anonymous volume
    env_file: ./.env.dev
    command: npm run dev
    environment: 
      - SESSION_SECRET="don't get cocky"