version: "3"
volumes:
  production-database:
services: 
  nginx:
    ports:
      - 80:80

  app: 
    build: 
      context: .
      args: 
        NODE_ENV: production
    env_file: ./.env.prod
    command: npm run start

  database:
    volumes:
      - production-database:/data/db # Named volume